version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - .:/app
      - db_data:/app/data
    command: gunicorn wsgi:app -b 0.0.0.0:80 --reload --worker-class gevent --timeout 300
volumes:
  # Define the named volume for the database
  db_data: